/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EmployerDatabase;

import java.sql.*;
import java.sql.PreparedStatement;
import java.text.MessageFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTable.PrintMode;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class EmployerDatabase extends javax.swing.JFrame {

   Connection conn =null;
   PreparedStatement pst=null;
   ResultSet rs=null;
   DefaultTableModel model=new DefaultTableModel();
   
   public EmployerDatabase() {
        initComponents();
        conn = EmployerDatabase.ConnectDb();
        
        Object col[]={"EmpID","NiNumber","Firstname","Surname","Gender","DOB","Age","Salary"};
        model.setColumnIdentifiers(col);
        jTable1.setModel(model);
        
         updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public static Connection ConnectDb(){
        try{
            Class.forName("org.sqlite.JDBC");
            Connection conn = DriverManager.getConnection("jdbc:sqlite:Employee.db");
            return conn;
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
            return null;
        }
    
    
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtDO = new javax.swing.JLabel();
        jtxtDOB = new javax.swing.JTextField();
        jbtnPrint = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jtxtSalar = new javax.swing.JLabel();
        jtxtSalary = new javax.swing.JTextField();
        jtxtEmployeeI = new javax.swing.JLabel();
        jtxtSurnam = new javax.swing.JLabel();
        jtxtSurname = new javax.swing.JTextField();
        jtxtGende = new javax.swing.JLabel();
        jtxtGender = new javax.swing.JTextField();
        jtxtFirstnam = new javax.swing.JLabel();
        jtxtFirstname = new javax.swing.JTextField();
        jtxtNINumbe = new javax.swing.JLabel();
        jtxtNINumber = new javax.swing.JTextField();
        jTextEmployeeID = new javax.swing.JTextField();
        jbtnAddData = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnClearData = new javax.swing.JButton();
        jtxtAg = new javax.swing.JLabel();
        jtxtAge = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtDO.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtDO.setText("DOB");
        getContentPane().add(jtxtDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, -1, -1));

        jtxtDOB.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(jtxtDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 140, -1));

        jbtnPrint.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 610, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "NI Number", "Firstname", "Surname", "Gender", "DOB", "Age", "Salary"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 680, -1));

        jtxtSalar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtSalar.setText("Salary");
        getContentPane().add(jtxtSalar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 530, -1, -1));

        jtxtSalary.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(jtxtSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 530, 140, -1));

        jtxtEmployeeI.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtEmployeeI.setText("Employee ID");
        getContentPane().add(jtxtEmployeeI, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        jtxtSurnam.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtSurnam.setText("Surname");
        getContentPane().add(jtxtSurnam, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        jtxtSurname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(jtxtSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 140, -1));

        jtxtGende.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtGende.setText("Gender");
        getContentPane().add(jtxtGende, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));

        jtxtGender.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(jtxtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 140, -1));

        jtxtFirstnam.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtFirstnam.setText("Firstname");
        getContentPane().add(jtxtFirstnam, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        jtxtFirstname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(jtxtFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 140, -1));

        jtxtNINumbe.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtNINumbe.setText("NI Number");
        getContentPane().add(jtxtNINumbe, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        jtxtNINumber.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(jtxtNINumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 140, -1));

        jTextEmployeeID.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextEmployeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEmployeeIDActionPerformed(evt);
            }
        });
        getContentPane().add(jTextEmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 140, -1));

        jbtnAddData.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnAddData.setText("Add Data");
        jbtnAddData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddDataActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnAddData, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 610, -1, -1));

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 610, -1, -1));

        jbtnClearData.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnClearData.setText("Clear Data");
        jbtnClearData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearDataActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnClearData, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 610, -1, -1));

        jtxtAg.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtAg.setText("Age");
        getContentPane().add(jtxtAg, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, -1, -1));

        jtxtAge.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(jtxtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 140, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Emloyee Database Management Systems");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        txt_search.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        getContentPane().add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 150, 40));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Search By Firstname");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, -1, 20));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextEmployeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEmployeeIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEmployeeIDActionPerformed
    private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        
        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit","Employee Database Management System",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
            System.exit(0);
        };
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnClearDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClearDataActionPerformed
        jTextEmployeeID.setText(null);
        jtxtNINumber.setText(null);
        jtxtFirstname.setText(null);
        jtxtSurname.setText(null);
        jtxtGender.setText(null);
        jtxtDOB.setText(null);
        jtxtAge.setText(null);
        jtxtSalary.setText(null);
    }//GEN-LAST:event_jbtnClearDataActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        MessageFormat header = new MessageFormat("Printing In Progress");
        MessageFormat footer = new MessageFormat("Page [0,number, integer]");
        try
        {
            jTable1.print(JTable.PrintMode.NORMAL,header,footer);
        }
        catch (java.awt.print.PrinterException e)
        {
            System.err.format("No Printer found", e.getMessage());
        }
        
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jbtnAddDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddDataActionPerformed
        String sql="INSERT INTO Employee(EmpID,NiNumber,Firstname,Surname,Gender,DOB,Age,Salary)VALUES(?,?,?,?,?,?,?,?)";
        try{
            pst=conn.prepareStatement(sql);
            pst.setString(1,jTextEmployeeID.getText());
            pst.setString(2,jtxtNINumber.getText());
            pst.setString(3,jtxtFirstname.getText());
            pst.setString(4,jtxtSurname.getText());
            pst.setString(5,jtxtGender.getText());
            pst.setString(6,jtxtDOB.getText());
            pst.setString(7,jtxtAge.getText());
            pst.setString(8,jtxtSalary.getText());
            
            pst.execute();
            JOptionPane.showMessageDialog(null,"System Update Completed");
            
            rs.close();
            pst.close();
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        updateTable();
        }
        
        public void updateTable(){
            conn= EmployerDatabase.ConnectDb();
            if(conn!=null)
            {
                String sql="Select EmpID,NINumber,Firstname,Surname,Gender,DOB,Age,Salary from Employee";
                
                try{
                    pst= conn.prepareStatement(sql);
                    rs=pst.executeQuery();
                    Object[] columnData= new Object[8];
                    
                    while (rs.next())
                            {
                                columnData[0]=rs.getString("EmpID");
                                columnData[1]=rs.getString("NINumber");
                                columnData[2]=rs.getString("Firstname");
                                columnData[3]=rs.getString("Surname");
                                columnData[4]=rs.getString("Gender");
                                columnData[5]=rs.getString("DOB");
                                columnData[6]=rs.getString("Age");
                                columnData[7]=rs.getString("Salary");
                                model.addRow(columnData);
                            }
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,e);
                }
                
            
            }
        
    }//GEN-LAST:event_jbtnAddDataActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
      try{
          String sql="select * from Employee where Firstname=? ";
          pst=conn.prepareStatement(sql);
          pst.setString(1,txt_search.getText());
          rs=pst.executeQuery();
          if(rs.next())
          {
              String add1=rs.getString("EmpID");
              jTextEmployeeID.setText(add1);
              String add2=rs.getString("NINumber");
        jtxtNINumber.setText(add2);
        String add3=rs.getString("Firstname");
        jtxtFirstname.setText(add3);
        String add4=rs.getString("Surname");
        jtxtSurname.setText(add4);
        String add5=rs.getString("Gender");
        jtxtGender.setText(add5);
        String add6=rs.getString("DOB");
        jtxtDOB.setText(add6);
        String add7=rs.getString("Age");
        jtxtAge.setText(add7);
        String add8=rs.getString("Salary");
        jtxtSalary.setText(add8);
              
          }
      }
      catch(Exception e)
      {
          JOptionPane.showMessageDialog(null,e);
      }
    }//GEN-LAST:event_txt_searchKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
new Front_Page().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployerDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployerDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployerDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployerDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployerDatabase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextEmployeeID;
    private javax.swing.JButton jbtnAddData;
    private javax.swing.JButton jbtnClearData;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JLabel jtxtAg;
    private javax.swing.JTextField jtxtAge;
    private javax.swing.JLabel jtxtDO;
    private javax.swing.JTextField jtxtDOB;
    private javax.swing.JLabel jtxtEmployeeI;
    private javax.swing.JLabel jtxtFirstnam;
    private javax.swing.JTextField jtxtFirstname;
    private javax.swing.JLabel jtxtGende;
    private javax.swing.JTextField jtxtGender;
    private javax.swing.JLabel jtxtNINumbe;
    private javax.swing.JTextField jtxtNINumber;
    private javax.swing.JLabel jtxtSalar;
    private javax.swing.JTextField jtxtSalary;
    private javax.swing.JLabel jtxtSurnam;
    private javax.swing.JTextField jtxtSurname;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
